_version: 1.2

defaults:
    - _self_
    - dataset: AdvTest_Finetune_train
    - training: single

model_name_or_path: microsoft/unixcoder-base
project_name: "CS+FL"
dataset_name: 'AdvTest_Finetune_train'
isWANDB: false

code_length: 256
nl_length: 128

train_batch_size: 1
eval_batch_size: 64
learning_rate: 2e-5
max_grad_norm: 1.0    

seed: 123456
n_gpu: 1
device: 'cpu'


