# Training
output_dir: saved_models/cosqa
do_eval: false
do_test: false
do_train: true
do_zero_shot: false
train_data_file: dataset/cosqa/cosqa-retrieval-train-19604.json
eval_data_file: dataset/cosqa/cosqa-retrieval-dev-500.json
codebase_file: dataset/cosqa/code_idx_map.txt
num_train_epochs: 10